<a href="https://colab.research.google.com/github/chettz/Backpropagation/blob/main/backpropagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import pandas as pd

# 시그모이드 함수
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
# 시그모이드 미분 함수
def sigmoid_derivative(x):
    return x * (1 - x)
# 제곱오차 계산 함수
def calculate_squared_error(output, target):
    return 0.5 * np.sum((output - target) ** 2)

# 신경망 초기화
input_size = 12
hidden_size = 3
output_size = 2

# 학습률 설정
learning_rate = 0.2

# 가중치 정규분포 난수로 초기화
weights_input_hidden = np.random.normal(0, 1, (input_size, hidden_size))
weights_hidden_output = np.random.normal(0, 1, (hidden_size, output_size))

# 편향 정규분포 난수로 초기화
bias_hidden = np.random.normal(0, 1, hidden_size)
bias_output = np.random.normal(0, 1, output_size)

# 입력데이터
train_data = np.array([[1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1],
              [0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1],
              [1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1],
              [1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0],
              [1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1],
              [0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1],
              [0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1],
              [0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1],
              [0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0],
              [0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1],
              [1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0],
              [0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0],
              [1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0],
              [1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0],
              [1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0],
              [1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1],
              [1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1],
              [1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1],
              [1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1],
              [1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1],
              [1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1],
              [0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1],
              [0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1],
              [0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1],
              [0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1],
              [0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1],
              [0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1],
              [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1],
              [1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1],
              [1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1],
              [1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1],
              [1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1], #32
              [0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0],
              [1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0],
              [1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0],
              [0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0],
              [0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0],
              [0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
              [1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0],
              [1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
              [1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1],
              [0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0],
              [0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0],
              [1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0],
              [1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0],
              [0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0],
              [0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0],
              [0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1],
              [1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1],
              [1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0],
              [0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1],
              [1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0],
              [1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0],
              [1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0],
              [1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0],
              [0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0],
              [1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0],
              [1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1],
              [0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0],
              [0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0],
              [0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0],
              [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0],
              [0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
              [0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0],
              [0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0],
              ])
# 정답 데이터
target_data_0 = np.array([1, 0])
target_data_1 = np.array([0, 1])

# 학습
for epoch in range(50):  # 50번의 학습 반복
    total_error = 0
    for i, data in enumerate(train_data):
        # forward process
        hidden_layer_input = np.dot(data, weights_input_hidden) + bias_hidden
        hidden_layer_output = sigmoid(hidden_layer_input)

        output_layer_input = np.dot(hidden_layer_output, weights_hidden_output) + bias_output
        output_layer_output = sigmoid(output_layer_input)

        # 정답 출력과의 오차 계산
        if i < 32:
          squared_error = calculate_squared_error(output_layer_output, target_data_0)
          # 출력층 error of unit 계산
          output_error = output_layer_output - target_data_0
          output_delta = output_error * sigmoid_derivative(output_layer_output)
        else:
          squared_error = calculate_squared_error(output_layer_output, target_data_1)
          # 출력층 error of unit 계산
          output_error = output_layer_output - target_data_1
          output_delta = output_error * sigmoid_derivative(output_layer_output)
        total_error += squared_error

        # backpropagate
        # 은닉층 오차(은닉층 error of unit = delta 계산)
        hidden_error = output_delta.dot(weights_hidden_output.T) #출력층의 델타와 은닉층(전치)의 가중치 곱
        hidden_delta = hidden_error * sigmoid_derivative(hidden_layer_output)

        # 가중치와 편향 업데이트
        weights_hidden_output -= learning_rate * hidden_layer_output[:, None].dot(output_delta[None, :])
        bias_output -= learning_rate * output_delta

        weights_input_hidden -= learning_rate * data[:, None].dot(hidden_delta[None, :])
        bias_hidden -= learning_rate * hidden_delta

print("Final weights and biases after training:")
print("weights_input_hidden:", weights_input_hidden)
print("weights_hidden_output:", weights_hidden_output)
print("bias_hidden:", bias_hidden)
print("bias_output:", bias_output)
print("Total Error" , total_error)


Final weights and biases after training:
weights_input_hidden: [[-1.12127516  0.46820764 -0.35371111]
 [-0.27364846 -0.6488628   2.17108711]
 [ 0.37941362  0.730324   -1.30639808]
 [ 0.78692599  1.50106356 -0.95270615]
 [ 0.7408248  -0.46016805  1.75063036]
 [-0.62187657  0.66705314 -1.66048628]
 [-0.59822833  1.73470934 -1.89097828]
 [-0.11000703 -1.56990667  0.67104882]
 [ 1.21401463  1.45058463 -1.01799596]
 [-1.49569286  0.46363792 -0.68759705]
 [ 2.27706102 -0.96409469  1.43697896]
 [ 0.10128357  0.36245673 -0.71816933]]
weights_hidden_output: [[-0.0922626   0.6091412 ]
 [ 3.20563653 -3.03742079]
 [-3.77453889  3.8635466 ]]
bias_hidden: [ 0.704547   -1.7388206   0.81315438]
bias_output: [ 0.2845307  -0.83967969]
Total Error 0.25622948581144717


In [8]:
test_data = [0,1,0,1,0,1,1,0,1,1,0,1]
print("Testing NeurlNetwork")


# 순전파
hidden_layer_input = np.dot(test_data, weights_input_hidden) + bias_hidden
hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_input = np.dot(hidden_layer_output, weights_hidden_output) + bias_output
output_layer_output = sigmoid(output_layer_input)

# 출력값과 범주 판단
# 가장 큰 값을 가진 인덱스 반환, 가장 큰 값의 인덱스가 0이면
# 출력층의 첫번째 출력 값이 크다는 의미이므로 test_data는 필기체 숫자 0으로 판단
category = 0 if np.argmax(output_layer_output) == 0 else 1
print(f"Test Data Output: {output_layer_output}, Predicted Category: {category}")

Testing NeurlNetwork
Test Data Output: [0.9646267  0.03047688], Predicted Category: 0
