<a href="https://colab.research.google.com/github/chettz/Backpropagation/blob/main/backpropagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np
import pandas as pd

# 시그모이드 함수
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
# 시그모이드 미분 함수
def sigmoid_derivative(x):
    return x * (1 - x)
# 제곱오차 계산 함수
def calculate_squared_error(output, target):
    return 0.5 * np.sum((output - target) ** 2)

# 신경망 초기화
input_size = 12
hidden_size = 3
output_size = 2

# 학습률 설정
learning_rate = 0.2

# 가중치 정규분포 난수로 초기화
weights_input_hidden = np.random.normal(0, 1, (input_size, hidden_size))
weights_hidden_output = np.random.normal(0, 1, (hidden_size, output_size))

# 편향 정규분포 난수로 초기화
bias_hidden = np.random.normal(0, 1, hidden_size)
bias_output = np.random.normal(0, 1, output_size)

# 입력데이터
train_data = np.array([[1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1],
              [0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1],
              [1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1],
              [1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0],
              [1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1],
              [0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1],
              [0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1],
              [0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1],
              [0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0],
              [0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1],
              [1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0],
              [0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0],
              [1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0],
              [1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0],
              [1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0],
              [1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1],
              [1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1],
              [1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1],
              [1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1],
              [1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1],
              [1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1],
              [0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1],
              [0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1],
              [0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1],
              [0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1],
              [0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1],
              [0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1],
              [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1],
              [1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1],
              [1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1],
              [1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1],
              [1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1], #32
              [0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0],
              [1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0],
              [1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0],
              [0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0],
              [0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0],
              [0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
              [1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0],
              [1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
              [1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1],
              [0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0],
              [0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0],
              [1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0],
              [1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0],
              [0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0],
              [0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0],
              [0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1],
              [1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1],
              [1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0],
              [0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1],
              [1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0],
              [1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0],
              [1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0],
              [1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0],
              [0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0],
              [1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0],
              [1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1],
              [0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0],
              [0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0],
              [0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0],
              [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0],
              [0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
              [0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0],
              [0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0],
              ])
# 정답 데이터
target_data_0 = np.array([1, 0])
target_data_1 = np.array([0, 1])

# 학습
for epoch in range(50):  # 50번의 학습 반복
    total_error = 0
    for i, data in enumerate(train_data):
        # forward process
        hidden_layer_input = np.dot(data, weights_input_hidden) + bias_hidden
        hidden_layer_output = sigmoid(hidden_layer_input)

        output_layer_input = np.dot(hidden_layer_output, weights_hidden_output) + bias_output
        output_layer_output = sigmoid(output_layer_input)

        # 정답 출력과의 오차 계산
        if i < 32:
          squared_error = calculate_squared_error(output_layer_output, target_data_0)
          # 출력층 error of unit 계산
          output_error = output_layer_output - target_data_0
          output_delta = output_error * sigmoid_derivative(output_layer_output)
        else:
          squared_error = calculate_squared_error(output_layer_output, target_data_1)
          # 출력층 error of unit 계산
          output_error = output_layer_output - target_data_1
          output_delta = output_error * sigmoid_derivative(output_layer_output)
        total_error += squared_error

        # backpropagate
        # 은닉층 오차(은닉층 error of unit = delta 계산)
        hidden_error = output_delta.dot(weights_hidden_output.T) #출력층의 델타와 은닉층(전치)의 가중치 곱
        hidden_delta = hidden_error * sigmoid_derivative(hidden_layer_output)

        # 가중치와 편향 업데이트
        weights_hidden_output -= learning_rate * hidden_layer_output[:, None].dot(output_delta[None, :])
        bias_output -= learning_rate * output_delta

        weights_input_hidden -= learning_rate * data[:, None].dot(hidden_delta[None, :])
        bias_hidden -= learning_rate * hidden_delta

print("Final weights and biases after training:")
print("weights_input_hidden:", weights_input_hidden)
print("weights_hidden_output:", weights_hidden_output)
print("bias_hidden:", bias_hidden)
print("bias_output:", bias_output)
print("Total Error" , total_error)


Final weights and biases after training:
weights_input_hidden: [[-0.63275499 -0.68862512  0.58411587]
 [ 1.00491453 -1.11733269 -0.39776434]
 [-1.35228761  0.99531305  0.48526976]
 [-1.07648373 -1.25652895  1.66097192]
 [ 1.1992626  -1.15659088 -1.67050354]
 [-1.18396785  0.25032803  1.24836254]
 [-0.91966997  0.02250459  0.47346883]
 [ 1.83675448  0.36091146 -0.52595361]
 [-1.11035272 -0.65048757  0.57455468]
 [-2.22540656  0.03601561  0.10101442]
 [ 2.4721489  -0.22812328 -0.13439348]
 [-1.43786375 -1.23893702  1.43672491]]
weights_hidden_output: [[-4.51621112  4.62087655]
 [-1.48640746 -0.72660804]
 [ 2.67044619 -2.21703694]]
bias_hidden: [ 0.25496941 -0.32327334 -1.69015669]
bias_output: [ 0.84825351 -1.03417834]
Total Error 0.22689689133858265


In [10]:
test_data = [0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1] # 필기체 숫자 0
print("Testing NeuralNetwork")


# 순전파
hidden_layer_input = np.dot(test_data, weights_input_hidden) + bias_hidden
hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_input = np.dot(hidden_layer_output, weights_hidden_output) + bias_output
output_layer_output = sigmoid(output_layer_input)

# 출력값과 범주 판단
# 가장 큰 값을 가진 인덱스 반환, 가장 큰 값의 인덱스가 0이면
# 출력층의 첫번째 출력 값이 크다는 의미이므로 test_data는 필기체 숫자 0으로 판단
category = 0 if np.argmax(output_layer_output) == 0 else 1
print(f"Test Data Output: {output_layer_output}, 판정 : {category}")


test_data = [0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0] # 필기체 숫자 1
print("Testing NeuralNetwork")


# 순전파
hidden_layer_input = np.dot(test_data, weights_input_hidden) + bias_hidden
hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_input = np.dot(hidden_layer_output, weights_hidden_output) + bias_output
output_layer_output = sigmoid(output_layer_input)

# 출력값과 범주 판단
# 가장 큰 값을 가진 인덱스 반환, 가장 큰 값의 인덱스가 0이면
# 출력층의 첫번째 출력 값이 크다는 의미이므로 test_data는 필기체 숫자 0으로 판단
category = 0 if np.argmax(output_layer_output) == 0 else 1
print(f"Test Data Output: {output_layer_output}, 판정 : {category}")

Testing NeuralNetwork
Test Data Output: [0.9646267  0.03047688], 판정 : 0
Testing NeuralNetwork
Test Data Output: [0.02833386 0.97273962], 판정 : 1
